// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/config"
	"application/src/controller"
	"application/src/repository"
	"application/src/server"
	"application/src/usecase"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func wireApp(cfg *config.ViperConfig, logger *zap.Logger) (*gin.Engine, error) {
	dataSource, err := repository.NewDataSource(logger, cfg)
	if err != nil {
		return nil, err
	}
	healthzRepoInterface := repository.NewHealthzRepo(logger, dataSource)
	healthzUseCaseInterface := usecase.NewHealthzUseCase(healthzRepoInterface, logger)
	healthzService := controller.NewHealthzService(healthzUseCaseInterface, logger)
	userRepoInterface := repository.NewUserRepo(logger, dataSource)
	userUseCaseInterface := usecase.NewUserUseCase(userRepoInterface, logger)
	userService := controller.NewUserService(userUseCaseInterface, logger)
	engine := server.NewGinServer(cfg, logger, healthzService, userService)
	return engine, nil
}
